# Generated by Django 2.0.3 on 2018-04-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbeystore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
    ]
