# Generated by Django 2.0.3 on 2018-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbeystore', '0003_auto_20180410_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='tbeystore/static/images/products'),
        ),
    ]
