# Generated by Django 2.0.3 on 2018-04-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbeystore', '0004_auto_20180410_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/tbeystore/images/products'),
        ),
    ]
