# Generated by Django 2.0.3 on 2018-04-11 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tbeystore', '0008_auto_20180410_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(default='placeholder', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='product_order',
            old_name='order_count',
            new_name='product_count',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='user',
        ),
        migrations.AddField(
            model_name='product_order',
            name='vendor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tbeystore.Vendor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbeystore.Product'),
        ),
        migrations.AddField(
            model_name='product_order',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tbeystore.Order'),
            preserve_default=False,
        ),
    ]
