# Generated by Django 2.0.3 on 2018-04-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbeystore', '0009_auto_20180410_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_order',
            name='product_count',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='vendor',
        ),
    ]
