# Generated by Django 2.0.3 on 2018-04-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbeystore', '0010_auto_20180411_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='comment',
        ),
    ]
