# Generated by Django 2.0.3 on 2018-04-11 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbeystore', '0012_auto_20180411_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
