# Generated by Django 2.0.3 on 2018-04-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbeystore', '0013_auto_20180411_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='product_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_order',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
