# Generated by Django 2.0.3 on 2018-04-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbeystore', '0014_auto_20180411_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=9),
        ),
    ]
